apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # this defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect ot (eg browser)
  selector:
    app: webapp
    release: 0-5
  ports:
  - port: 80
    name: http
    nodePort: 30080

  type: NodePort
